default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: locations-app_development

test:
  <<: *default
  database: locations-app_test

production:
  <<: *default
  database: locations-app_production
  username: location-app
  password: <%= ENV['LOCATION-APP_DATABASE_PASSWORD'] %>
