# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e394ac5eef334a3e329c13d1161a26977de0b10369d993078180d8dd8ca624c36be28b0308eaf6deb0935bcb2e20730099f73ba81125b9e1268a7291e16e29ac

test:
  secret_key_base: 8c921bd87dcc173215954e8a4d1129d2fd14fbf448b8d2ed3bd43b08e8a7eabd59be5349498ff7c3c4179b0e8268891f98dc9e60a844e1b29beb8de7dcf9f320

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
